### ISSUE TITLE
Add rsnapshot and openmediavault-backups as well as plexmediaserver database to exclude list

### ISSUE THREAD

**Issue by henfri** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#11]
Hello,

snapraid does not like:
-files that change without the date of the file changing
-hardlinks changing

Thus, every snapraid-sync complains about data from rsnapshot, openmediavault-backups and the plexmediaserver database (there may be others). 

I suggest adding these directories automatically to the snapraid-exclude list.
Be aware that the path in the exclude-list starts at the pool level.
E.g. do not put /media/UU-I-D/plexmediaserver/, but just /plexmediaserver/ into the exclude.

Regards,
Hendrik

**Comment by ryecoaaron** [comment]
Are you asking for the plugin to figure out where the rsnapshot, plex, and backup directories are and exclude them?  I'm not sure this should be in the snapraid plugin since you can add excludes.

**Comment by henfri** [comment]
Hello,

yes, I think that this should be automated. That's what I would expect of a userfriendly solution.
For all rsnapshot/plex/omv-backup that is configured via OMV-Gui this should also be determinable, no?

Yes, one can add exclude manually, but it is not userfriendly and I expect that 99.9% of users would do this only afrter finding out that it is needed by seeing the errors in the logs of Snapraid and after research.

Greetings,
Hendrik

**Comment by ryecoaaron** [comment]
Personally, I think this would be difficult to maintain.  While you only have those three plugins that need exclusions, other people going to come up with others.  I guess I don't understand why you couldn't just copy and paste the directories from the snapraid output causing errors into exclusions.

**Comment by henfri** [comment]
Hello,

for me, having an 'integrated' solution like OMV means, that interdependancies are taken into account, rather that 'just' having a nice Web-Interface.

I agree, that it is not easy to maintain, but with three plugins, we have a start. We can extend it.

Of course I can just put in the directories -and I did. For me: Job done. But I am thinking of the product and for others.

For me, the difficulty was:
1) Snapraid reported files being *corrupt* I almost 'fixed' them (restoring the old version from the last sync). Only after asking in the snapraid forum I found that this is a problem with the time-stamps (as outlined in my first post). Do we expect every user to make this learning?
2) The patterns and wildcards to exclude files in snapraid are not straight forward
 a) patterns do not match "/"
 b) patterns start at array level and not at the filesystem root ("/")
Again: Do we expect every user to make this learning?

Greetings,
Hendrik

**Comment by ryecoaaron** [comment]
When you say "we can extend it", who is the "we"?

Actually, it would be nice if users learn something about snapraid.  Users put too much faith in automatic things sometimes.

Also, if the system backup and/or plex database are on the drive in the array that fail, the user is out of luck because those files are excluded?  snapraid isn't just about redundancy.  So, people who use rsnapshot can't have their data protected from integrity errors?  This really makes me wonder how useful the plugin is then.

**Comment by henfri** [comment]
Hello Aaron,

"we" is the user who finds the problem and proposes a solution (here me) and the developer who can implement it (here: you).

I did learn something about snapraid. And I want to share this and make sure that others do not have to learn it the hard way, just like me.

For plex: Yes: The user would be out of luck. What's the alternative? Today, every snapraid sync will show an error in the plex folder. For me that meant 'getting used to snapraid errors' and ignoring them. And then, another snapraid error developed. I kept ignoring the mails (as I was used to these errors). That is not the better option.

For rsnapshot: well, a backup of a backup... That would be ok for me, not to have.

I am open for other proposals. But the status quo is not ok.

Greetings,
Hendrik

**Comment by ryecoaaron** [comment]
I figured the part involving the most work would be me.

If you learned something about snapraid then why not improve documentation instead of trying to make every little thing automatic and a pain to maintain?

I don't use or like plex. So, I don't know what to do for that.

I do use rsnapshot and the backup plugin.  I'm not sure what "a backup of a backup" means but if you only have one backup, it is not good.  For me, excluding everything rsnapshot and the backup plguin does is unacceptable.

The plugin is almost four years old to the day and has almost 200 commits.  Not sure how it is staying at status quo.

I don't have any other proposals.  I thought picking the volume and adding a folder browser would make it easy enough to find your plex, rsnapshot, etc folders to exclude.  It automatically puts the relative path in.

**Comment by henfri** [comment]
Hello,

I am sorry, that I cannot help more (i.e. taking work off of you). But be assured: i don't do this for me. For me it is fixed already.

Why not improve the documentation? Because noone reads it. Sorry.

"a backup of a backup": Rsnapshot is a Backup. Snapraid is a Backup as well. So, the rsnapshot folders do not need to go into the snapraid backup.

>Not sure how it is staying at status quo.
Status quo on the issue that I report.

>..make it easy enough..
Well, it is good. But I was not aware one could do that. My bad. Reading the documentation (where?) would probably have helped.

But it is not good enough. The user need to be informed that this can be a problem and asked if he wants to exclude these paths.
