### ISSUE TITLE
Support of split parity files

### ISSUE THREAD

**Issue by Tobi90as** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#12]
Hello,
I wondered if it would be possible to implement the support of splitting a parity file over multiple disks as mentioned here: [https://sourceforge.net/p/snapraid/discussion/1677233/thread/ca80543b/](https://sourceforge.net/p/snapraid/discussion/1677233/thread/ca80543b/)
Of course I could edit the configuration file manually, but any change in the Web-GUI of openmediavault would probably overwrite my changes I guess.
As I guess this shouldn't be that much of an effort I thought it could be worth suggesting this feature to be implemented already in the plugin.

Thanks for any reply.
Tobi

**Comment by ryecoaaron** [comment]
I will look at this.  This is more work than you think since upgrades have to be converted and split parity over multiple levels of parity are allowed.  This requires database, web interface, and config creation changes.

**Comment by Tobi90as** [comment]
Well indeed it seems I understand too little of it. Thanks for looking at this anyway.
Just out of curiosity: So the main difficulty is to keep track of the distribution of multiple levels of parity over multiple disks? I thought this would be the job of snapraid and not of the plugin. What do you mean by upgrades have to be converted?

**Comment by ryecoaaron** [comment]
Currently the plugin increments a counter every time a disk is marked as a parity disk.  This tells snapraid which parity file it is.  When looping through the disks, there is no chance to write multiple disks to one parity line let alone knowing which parity level it is.

So, I need to figure out how best to present a web interface option to select which parity level the drive will be associated with and write the parity lines in the config file after looping through the disk list in the database.

I also need to figure out how to upgrade the database fields for people already running the plugin not using split parity so that their config does not change causing them problems.  People who install plugin updates shouldn't have to reconfigure anything just to keep their system working.

**Comment by Tobi90as** [comment]
I understand, thanks for that detailed answer.

**Comment by ryecoaaron** [comment]
6.2 in the testing repo now supports split parity.
