### ISSUE TITLE
Allow user to disable default exclusion list

### ISSUE THREAD

**Issue by u1735067** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#14]
The default list contain a dangerous default to me, "*.bak" (https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/blob/master/usr/share/openmediavault/mkconf/snapraid#L105), could you add an option to disable this list ?
Or maybe prepopulate it to the Rule list instead of forcing it ?

**Comment by ryecoaaron** [comment]
Why is it dangerous?  The pre-defined list is to add files that most people wouldn't know to exclude.

**Comment by Alex131089** [comment]
Dangerous to me*, because I want that files to be included too (they're not "system" files to me).

**Comment by ryecoaaron** [comment]
Well, *.bak has been in the plugin for over four years and you are the first to have an issue with it.  Did you try overriding it by creating a *.bak inclusion?

**Comment by Alex131089** [comment]
I feel dumb not having though of using inclusion, but if I understand http://www.snapraid.it/manual, the exclude rule will match first and there's no chance for the include rule.
Also, before creating the issue and trying again now, I previously failed to try to create global ("file") rules because the UI is forcing to select a drive, which makes no sense for a global ("file") rule.

And if I understand the manual correctly again, be ending the rules with an inclusion, every other files (non matching) would be ignored (excluded), so I'd have to add something like `include *`, or add another exclude rule (but which one)?

I have no problem with having defaults, but here the user have to edit `/usr/share/openmediavault/mkconf/snapraid` (and hope an update will not revert it) to override the default ..
Wouldn't it better to prepopulate the rules with those defaults ?

**Comment by ryecoaaron** [comment]
I wrote the plugin and know the manual well.  I had just never tried including and excluding the same rule.  If it doesn't work, that is all I needed to know.  If you want to code the pre-populate code, send in a pull request. 

I will think about removing it but there may be a lot of people who have their syncs automated and will wonder why .bak files were all of a sudden added.

**Comment by Alex131089** [comment]
I'm sure you know it, I don't (I didn't mean to offense you or anything), this is my first real experience with snapraid (except from one test to experiment).
If I have time for this, I'll do it ; but I don't have knowledge of the OMV plugin system.
I wrote the steps I'd follow in https://github.com/Alex131089/openmediavault-snapraid/projects/1 .. but maybe there's a simpler solution (or a temporary one):
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/compare/master...Alex131089:Alex131089-excludes-2
What do you think of this one?
I don't know how the package update would be handled though, will debian / OMV replace the `omv_snapraid_excludes` file, or preserve it and install the new as `.dpkg-dist`, or ..?

**Comment by ryecoaaron** [comment]
I'm fine with the /etc/default/ file and that should allow your changes to survive upgrades.  Send a pull request my way and I will accept it.  I will fix the force filesystem selection in the next day or so.
